.catalog:
  name: "filebeat-alpine"
  version: "6.2.3"
  description: "Catalog's rancher-compose"
  minimun_rancher_version: v1.0.1
  maximun_rancher_version: v1.6.14
  upgrade_from: "1.0.0"
 
version: '2'
services:
  filebeat:
    scale: 1
    start_on_create: true
