.catalog:
  name: "mysql"
  version: "v0.0.1"
  description: "A recommended stack for the MySQL RDBMS."
  uuid: mysql-0
  minimum_rancher_version: v1.0.0
 
version: '2'
services:
  filebeat-test:
    scale: 1
    start_on_create: true
  filebeat:
    scale: 1
    start_on_create: true
