.catalog:
  name: "RMS-SC-Service"
  version: "0.0.1"
  description: "Catalog's rancher-compose"
  minimun_rancher_version: v1.0.1
  maximun_rancher_version: v1.6.14
  upgrade_from: "1.0.0"
 
version: '2'
services:
  sc-service-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: safeye-rms-sc-service
        source_port: 80
        target_port: 8083
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  safeye-rms-sc-service:
    scale: 2
    start_on_create: true