name: Filebeat-SW
description: Log Shipper to logstash

version: 6.2.3
category: Shipper
maintainer: "Anson Lu <lupc@safewaychina.com>"
license: MIT
projectURL: https://github.com/Pinary/rancher-cattle-apps.git
